[project]
name = "day02"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tushar1121s", email = "tusharkumarjuly14@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "groq>=1.6.0",
    "python-dotenv>=1.2.2",
]

[project.scripts]
day02 = "day02:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
